// tb_Render_Frame — renders one full 640x480 frame to a PGM image.
//
// Not a test: nothing here is asserted. This exists so the figures in the
// documentation are generated by the design itself rather than photographed off
// a monitor, which means they are pixel-exact and reproducible from `make`.
//
// tb_Char_Generator is the testbench that actually checks anything, and it runs
// on a shrunken frame so it is fast. This one runs at the real geometry, takes
// a while, and is invoked deliberately:
//
//   make sim TB=tb_Render_Frame
//   ffmpeg -y -i build/frame.pgm docs/render.png
//
// A photograph of the board is the evidence that the hardware works. This is
// evidence about the RTL. Label them accordingly.

`timescale 1ns/10ps

module tb_Render_Frame ();

  localparam c_CLOCK_PERIOD_NS = 40;

  localparam c_VIDEO_WIDTH = 3;
  localparam c_TOTAL_COLS  = 800;
  localparam c_TOTAL_ROWS  = 525;
  localparam c_ACTIVE_COLS = 640;
  localparam c_ACTIVE_ROWS = 480;

  localparam c_COLS      = 40;
  localparam c_ROWS      = 30;
  localparam c_ADDR_BITS = 11;

  localparam c_FRAME = c_TOTAL_COLS * c_TOTAL_ROWS;

  reg r_Clk = 1'b0;
  always #(c_CLOCK_PERIOD_NS/2) r_Clk <= !r_Clk;

  wire w_HSync_Start, w_VSync_Start;

  VGA_Sync_Pulses #(.TOTAL_COLS(c_TOTAL_COLS),
                    .TOTAL_ROWS(c_TOTAL_ROWS),
                    .ACTIVE_COLS(c_ACTIVE_COLS),
                    .ACTIVE_ROWS(c_ACTIVE_ROWS))
  VGA_Sync_Pulses_Inst
    (.i_Clk       (r_Clk),
     .o_HSync     (w_HSync_Start),
     .o_VSync     (w_VSync_Start),
     .o_Col_Count (),
     .o_Row_Count ());

  wire [c_ADDR_BITS-1:0]   w_Rd_Addr;
  wire                     w_HSync_CG, w_VSync_CG;
  wire [c_VIDEO_WIDTH-1:0] w_Red_Video, w_Grn_Video, w_Blu_Video;

  // Stand-in for Char_RAM, one clock of read latency.
  reg [7:0] r_Stub [0:(1<<c_ADDR_BITS)-1];
  reg [7:0] r_Rd_Data;

  always @(posedge r_Clk)
    r_Rd_Data <= r_Stub[w_Rd_Addr];

  Char_Generator #(.VIDEO_WIDTH(c_VIDEO_WIDTH),
                   .TOTAL_COLS(c_TOTAL_COLS),
                   .TOTAL_ROWS(c_TOTAL_ROWS),
                   .ACTIVE_COLS(c_ACTIVE_COLS),
                   .ACTIVE_ROWS(c_ACTIVE_ROWS),
                   .c_COLS(c_COLS),
                   .c_ROWS(c_ROWS),
                   .c_ADDR_BITS(c_ADDR_BITS))
  Char_Generator_Inst
    (.i_Clk       (r_Clk),
     .i_HSync     (w_HSync_Start),
     .i_VSync     (w_VSync_Start),
     .o_Rd_Addr   (w_Rd_Addr),
     .i_Rd_Data   (r_Rd_Data),
     .o_HSync     (w_HSync_CG),
     .o_VSync     (w_VSync_CG),
     .o_Red_Video (w_Red_Video),
     .o_Grn_Video (w_Grn_Video),
     .o_Blu_Video (w_Blu_Video));

  // Same capture as tb_Char_Generator: anchored only at the frame boundary,
  // free-running from there, so nothing about the DUT's own HSync positions it.
  reg [c_ACTIVE_COLS-1:0] r_Frame [0:c_ACTIVE_ROWS-1];

  reg [9:0] r_Cap_Col = 0;
  reg [9:0] r_Cap_Row = 0;
  reg       r_VSync_D = 1'b1;

  wire w_Frame_Start = w_VSync_CG & ~r_VSync_D;
  wire w_In_Active   = (r_Cap_Col < c_ACTIVE_COLS) && (r_Cap_Row < c_ACTIVE_ROWS);

  always @(posedge r_Clk)
  begin
    r_VSync_D <= w_VSync_CG;

    if (w_In_Active)
      r_Frame[r_Cap_Row][r_Cap_Col] <= w_Red_Video[0];

    if (w_Frame_Start)
    begin
      r_Cap_Col <= 1;
      r_Cap_Row <= 0;
    end
    else if (r_Cap_Col == c_TOTAL_COLS-1)
    begin
      r_Cap_Col <= 0;
      r_Cap_Row <= (r_Cap_Row == c_TOTAL_ROWS-1) ? 0 : r_Cap_Row + 1;
    end
    else
      r_Cap_Col <= r_Cap_Col + 1;
  end

  // ---------------------------------------------------------------------
  // Screen contents
  // ---------------------------------------------------------------------

  task BLANK_ALL;
    integer i;
    begin
      for (i = 0; i < (1<<c_ADDR_BITS); i = i + 1)
        r_Stub[i] = " ";
    end
  endtask

  // Writes a string starting at (col, row). Verilog right-justifies string
  // literals in the vector and pads with nulls, so the leading nulls are
  // skipped rather than written as characters.
  task PUT;
    input integer i_Col;
    input integer i_Row;
    input [8*40:1] i_Str;
    integer k, pos;
    reg [7:0] ch;
    begin
      pos = 0;
      for (k = 40; k >= 1; k = k - 1)
      begin
        ch = i_Str[k*8 -: 8];
        if (ch !== 8'h00)
        begin
          r_Stub[i_Row * c_COLS + i_Col + pos] = ch;
          pos = pos + 1;
        end
      end
    end
  endtask

  integer f, row, col;

  initial begin
    BLANK_ALL;

    PUT(4,  2, "SERIAL-CONTROLLED VGA DISPLAY");
    PUT(4,  4, "iCE40-HX1K  40x30 CHARACTER GRID");
    PUT(4,  6, "8x8 FONT ROM, DRAWN AT 2x");

    PUT(4,  9, " !\"#$%&'()*+,-./0123456789:;<=>?");
    PUT(4, 10, "@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_");
    PUT(4, 11, "`abcdefghijklmnopqrstuvwxyz{|}~");

    PUT(4, 14, "THE QUICK BROWN FOX JUMPS OVER");
    PUT(4, 15, "THE LAZY DOG 0123456789");

    PUT(4, 18, "RENDERED FROM SIMULATION BY");
    PUT(4, 19, "sim/tb_Render_Frame.v");

    // Two whole frames, so the captured image is entirely post-load.
    repeat (2 * c_FRAME) @(posedge r_Clk);

    // P2 is ASCII greyscale: no library, no encoding, just numbers.
    f = $fopen("frame.pgm", "w");
    $fwrite(f, "P2\n%0d %0d\n255\n", c_ACTIVE_COLS, c_ACTIVE_ROWS);
    for (row = 0; row < c_ACTIVE_ROWS; row = row + 1)
    begin
      for (col = 0; col < c_ACTIVE_COLS; col = col + 1)
        $fwrite(f, "%0d ", r_Frame[row][col] ? 255 : 0);
      $fwrite(f, "\n");
    end
    $fclose(f);

    $display("wrote frame.pgm (%0dx%0d)", c_ACTIVE_COLS, c_ACTIVE_ROWS);
    $finish;
  end

endmodule
