#!/usr/bin/env python3
"""Generate rtl/Font_ROM.v from tools/font8x8_basic.h.

The font ROM is emitted as Verilog source rather than loaded with $readmemh at
elaboration time. The Makefile hands files to yosys from the repo root but runs
vvp from inside build/, so no single relative path is correct for both; a
generated array sidesteps the question entirely.

The array is emitted as an initial block over a reg array, NOT as a case
statement. A case over the 10-bit address synthesizes to eight 10-input boolean
functions -- logic, not memory -- and there are only 1280 LUTs on an iCE40-HX1K.
As an initialized array with a synchronous read it infers as two EBRs and costs
no logic at all. See docs/design.md.

Usage:
    python3 tools/gen_font_rom.py               # -> rtl/Font_ROM.v
    python3 tools/gen_font_rom.py path/out.v
    make font
"""

import argparse
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

DEFAULT_SOURCE = REPO_ROOT / "tools" / "font8x8_basic.h"
DEFAULT_OUTPUT = REPO_ROOT / "rtl" / "Font_ROM.v"

GLYPHS = 128          # ASCII 0x00..0x7F
GLYPH_ROWS = 8        # 8x8 font, one byte per row
BYTE_RE = re.compile(r"0x([0-9A-Fa-f]{2})")
GLYPH_LINE_RE = re.compile(r"\{\s*0x")


def fail(message):
    """Abort loudly.

    A generator that quietly emits a short file gives you a font ROM that works
    for 'A' and is blank for 'p', and you find that out on a monitor. Every
    assumption about the source file is checked before anything is written.
    """
    sys.exit(f"gen_font_rom.py: {message}")


def parse_font(source):
    """Return a list of GLYPHS glyphs, each a list of GLYPH_ROWS byte values."""
    try:
        text = source.read_text()
    except OSError as exc:
        fail(f"cannot read {source}: {exc}")

    glyphs = []
    for lineno, line in enumerate(text.splitlines(), start=1):
        if not GLYPH_LINE_RE.search(line):
            continue          # license header, array declaration, closing brace
        row_bytes = [int(b, 16) for b in BYTE_RE.findall(line)]
        if len(row_bytes) != GLYPH_ROWS:
            fail(f"{source}:{lineno}: expected {GLYPH_ROWS} bytes, "
                 f"found {len(row_bytes)}")
        glyphs.append(row_bytes)

    if len(glyphs) != GLYPHS:
        fail(f"{source}: expected {GLYPHS} glyphs, found {len(glyphs)}")

    return glyphs


def art(row_byte):
    """Render one glyph row, bit 0 leftmost, as the font itself defines it."""
    return "".join("#" if row_byte >> col & 1 else "." for col in range(8))


def label(code):
    """A human-readable name for a character code, for the comments."""
    if 0x20 <= code <= 0x7E:
        return f"0x{code:02X} '{chr(code)}'"
    return f"0x{code:02X}"


def emit(glyphs, source):
    depth = GLYPHS * GLYPH_ROWS
    addr_bits = depth.bit_length() - 1

    out = []
    w = out.append

    w(f"// Font_ROM -- GENERATED FILE, DO NOT EDIT BY HAND.")
    w(f"//")
    w(f"// Generated by tools/gen_font_rom.py from {source.name}.")
    w(f"// Regenerate with `make font`.")
    w(f"//")
    w(f"// {GLYPHS} glyphs x {GLYPH_ROWS} rows = {depth} entries of 8 bits = "
      f"{depth * 8 // 1024} Kbit,")
    w(f"// which yosys infers as two iCE40 EBRs -- but only because the read")
    w(f"// below is synchronous. An asynchronous read cannot map to an EBR and")
    w(f"// would be built out of logic instead, which does not fit.")
    w(f"//")
    w(f"// Address layout: {{char_code[6:0], glyph_row[2:0]}}, so one glyph's")
    w(f"// eight rows are eight consecutive addresses and the address is pure")
    w(f"// concatenation with no adder.")
    w(f"//")
    w(f"// Bit order: bit 0 is the LEFTMOST pixel of a row. That is the reverse")
    w(f"// of the obvious guess, so the ASCII art beside each byte below shows")
    w(f"// the font as it will actually be drawn.")
    w(f"//")
    w(f"// Font: 8x8 monochrome bitmap font by Daniel Hepper, public domain,")
    w(f"// based on Marcel Sondaar / IBM public-domain VGA fonts. See")
    w(f"// {source.name} for the original notice.")
    w(f"")
    w(f"module Font_ROM")
    w(f"  (input             i_Clk,")
    w(f"   input      [{addr_bits - 1}:0]  i_Addr,")
    w(f"   output     [7:0]  o_Data);")
    w(f"")
    w(f"  localparam c_DEPTH     = {depth};")
    w(f"  localparam c_ADDR_BITS = {addr_bits};")
    w(f"")
    w(f"  reg [7:0] r_Mem [0:c_DEPTH-1];")
    w(f"  reg [7:0] r_Data = 8'h00;")
    w(f"")
    w(f"  initial begin")

    entries = 0
    for code, rows in enumerate(glyphs):
        w(f"    // {label(code)}")
        for row, value in enumerate(rows):
            addr = code * GLYPH_ROWS + row
            w(f"    r_Mem[{addr}] = 8'h{value:02X};  // {art(value)}")
            entries += 1

    w(f"  end")
    w(f"")
    w(f"  // Synchronous read: the address is registered and the data appears")
    w(f"  // one clock later. Char_Generator's pipeline is built around that")
    w(f"  // cycle -- see docs/design.md on pipeline alignment.")
    w(f"  always @(posedge i_Clk)")
    w(f"    r_Data <= r_Mem[i_Addr];")
    w(f"")
    w(f"  assign o_Data = r_Data;")
    w(f"")
    w(f"endmodule")
    w(f"")

    if entries != depth:
        fail(f"emitted {entries} entries, expected {depth}")

    return "\n".join(out)


def write_atomic(path, text):
    """Write via a temp file and rename.

    `make font` overwrites a file that is committed to the repo. If this script
    died partway through a direct write, or through a shell redirect, it would
    leave a truncated Font_ROM.v on top of a good one.
    """
    tmp = path.with_suffix(path.suffix + ".tmp")
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp.write_text(text)
        os.replace(tmp, path)
    except OSError as exc:
        tmp.unlink(missing_ok=True)
        fail(f"cannot write {path}: {exc}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate rtl/Font_ROM.v from an 8x8 font header.")
    parser.add_argument("output", nargs="?", type=Path, default=DEFAULT_OUTPUT,
                        help=f"output Verilog file (default: {DEFAULT_OUTPUT})")
    parser.add_argument("-s", "--source", type=Path, default=DEFAULT_SOURCE,
                        help=f"font header to read (default: {DEFAULT_SOURCE})")
    args = parser.parse_args()

    glyphs = parse_font(args.source)
    write_atomic(args.output, emit(glyphs, args.source))

    print(f"{args.output}: {GLYPHS} glyphs, {GLYPHS * GLYPH_ROWS} entries",
          file=sys.stderr)


if __name__ == "__main__":
    main()
